### ISSUE TITLE
-10 points in pub.dev for not supporting grpc last version

### ISSUE THREAD

**Issue by guyluz11** [cachapa/firedart#1] opened 2019-08-03 15:16 UTC
This library get -10 points in pub.dev site for not including the last version of grpc dependence.

"Support latest dependencies. (-10 points)

The version constraint in pubspec.yaml does not support the latest published versions for 1 dependency (grpc)."

![grpc_is_not_updated](https://user-images.githubusercontent.com/9304740/62413688-80557580-b61a-11e9-936f-4ec8bc758162.png)

**Comment by guyluz11** [comment] 2019-08-03 15:22
Just found out the comment in the code "grpc: ^1.0.3 # Flutter is currently incompatible with version 2.x".
Is it grpc library problem or is it just in this library?.

**Comment by guyluz11** [comment] 2019-08-03 15:28
Just found out the comment in the code

> grpc: ^1.0.3 # Flutter is currently incompatible with version 2.x.

From Grpc library 

> This library requires Dart SDK version 2.2.0 or later.

Flutter current version

>  environment:
>   sdk: ">=2.1.0 <3.0.0"

**Comment by guyluz11** [comment] 2019-09-17 12:13
Update

Grpc library can now work on Dark SDK 2.2.0
> This library requires Dart SDK version 2.2.0 or later.

protobuf library is not up-to-date -10 pints, we have `0.13.15` and last version is `0.14.3`

**Comment by cachapa** [comment] 2019-11-20 22:17
Again, sorry for only noticing this now.
Closing as the issue is now fixed.

**Closed by cachapa** 2019-11-20 22:17 UTC
