### ISSUE TITLE
isSignedIn Method always return false

### ISSUE THREAD

**Issue by mabedamro** [cachapa/firedart#81] opened 2021-12-17 11:25 UTC
after sign in with email and password , isSignedIn always return  false after restart the app

**Comment by lzzy12** [comment] 2022-01-18 11:40
Isn't that what should happen until you call logout( ) method?

**Comment by bksubhuti** [comment] 2023-08-09 03:18
seems to work fine for me.

**Comment by cachapa** [comment] 2023-08-09 07:44
Closing since it can't be reproduced.
It's likely the problem was missing token storage.

**Closed by cachapa** 2023-08-09 07:44 UTC
